name: Docker website CI
on:
  push:
    branches:
    - main
jobs:
  build:
    name: Build y push de la imagen
    runs-on: ubuntu-latest

    env: #Creo una variable con el nombre completo de la imagen
      IMG: mariocuee38/apachetest:latest

    steps:
    - name: Checkear repositorio
      uses: actions/checkout@v4.1.5

    - name: Login a Docker Hub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Hacer docker build
      run: |
        docker build --platform linux --tag $IMG -f Dockerfile .

    - name: Hacer push de la imagen a Docker Hub
      run: |
        docker push $IMG

    - name: Deployement en server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 3.82.175.207
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd deploy/base_soloanimales
          git pull origin main
          docker compose down
          docker compose pull apache
          docker compose up -d
