name: Docker website CI
on:
  push:
    branches: 
    - main
jobs:
  build:
    name: Build y push de la imagen
    runs-on: ubuntu-latest

    env: #Creo una variable con el nombre completo de la imagen
      IMG: ${{ secrets.DOCKERHUB_USERNAME }}/apachetest
    
    steps:
    - name: Checkear repositorio
      uses: actions/checkout@v4.1.5
      
    - name: Login a Docker Hub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Hacer docker build
      run: | 
        docker build --platform linux --tag $IMG -f Dockerfile .
    
    - name: Hacer push de la imagen a Docker Hub
      run: | 
        docker push $IMG
          
